### ISSUE TITLE
Unable to download layers

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-osm#35]
Looks like the ft-osm branch of the authoring tool is using the old folder in dropbox.

**Comment by panterz** [comment]
https://github.com/edina/fieldtrip-authoring-tool/commit/68db4e2775c5757346bc2de026aa97e044a84268

**Comment by gmh04** [comment]
This commit https://github.com/edina/pcapi/commit/977d764208f66c6d74483bd3cf283779e34dca59 (and from memory what we put on the white board) suggests the directory name in now 'features'.

App internal structure is documented here https://github.com/edina/fieldtrip-open/wiki/App-Directory-Structure.  Do we need something similar for dropbox / localprovider (for items used using /fs)?

**Comment by gmh04** [comment]
Authoring tool is hot fixed and 0.3.0 of the app contains this fix.  Not sure if I understand the download layers page, but i was able to download and enable a KML layer.
