### ISSUE TITLE
place search does not remember country last selected

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-osm#41]
If you select a country other than UIK, such as Germany, to do a search, the next time you do a search the selection defaults back to UK which is going to annoy users. Also this list is very long - is there any way we can introduce auto complete and/or filter?

**Comment by gmh04** [comment]
Ben I think its basing it on your location, not last search.

**Comment by benismobile** [comment]
ok - that seems more reasonable.

**Comment by benismobile** [comment]
ok think I'll close this. Might eb worth taking a look at filtering the country list at some point.
