### ISSUE TITLE
pcapi date filter format does not contain timezone information

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-osm#45]
To filter all records by date the date format is:

filter=date&start_date=20121101_12:00:00&end_date=20121105_12:00:00

This date format is not only non standard it does not contain timezone information.  This is just about OK for FTGB but not for FTOSM.  Perhaps we should be using UTC instead?

**Comment by gmh04** [comment]
So for example:

start_date=2015-05-15T14%3A46%3A12.205Z

This is an API change so would require the creation of pcapi 1.4.

**Comment by benismobile** [comment]
yep this makes sense. I guess we should consider bringing this forward to release for 1.5 so we can change existing records to use new date format as part of migration script?

**Comment by gmh04** [comment]
Records don't need changing, timestamps are stored as UTC.  This will be a change to AT and pcapi, I don't think the bug is serious enough for FTGB to delay release of 1.5.

**Comment by benismobile** [comment]
Ok that's great. please go ahead with new pcapi 1.4 as part of OSM release,

**Comment by gmh04** [comment]
https://github.com/edina/fieldtrip-authoring-tool/commit/088c4f5fdf068f8c029515dfe03636492a96c64e
