### ISSUE TITLE
Error fetching layers

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-osm#46]
Clicking on "Download Overlays" never finishes.  adb log error

"05-12 11:33:58.674 D/CordovaLog(10360): file:///android_asset/www/js/ext/jquery.js: Line 2 : Uncaught TypeError: Cannot read property 'length' of undefined"

**Comment by gmh04** [comment]
/1.3/pcapi/fs/dropbox/7JUipjz5m021SjFr/features/

on rainbow returns:

{"msg": "[404] u\"Path '/features' not found\"", "error": 1}

**Comment by panterz** [comment]
cause newest pcapi is not deployed where tiles/layers has been replaced as features as we discussed in the past
